name: Maven Build

env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

on:
  push:
    branches:
      - "main"
      - "feat/*"
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '.sdkmanrc'
      - 'README.md'
      - 'LICENSE'
      - 'CLAUDE.md'
      - '.junie/guidelines.md'
      - 'Taskfile.yml'
      - 'renovate.json'
      - '/docs'
      - '/docker'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: 'temurin'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw -Prelease -ntp verify

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarQube Analyze
        run: ./mvnw initialize sonar:sonar
